
tasks:
  - init: npm install
    command: |
      export HMR_HOST='gp url 3000' 
      echo "Starting dev server..."
      npm run dev

ports:
  - port: 5173
    onOpen: open-browser

vscode:
  extensions:
    - svelte.svelte-vscode